language: python
python:
- '2.7'
install: pip install . --use-mirrors
script: python setup.py nosetests
deploy:
  provider: pypi
  user: zvikagart
  password:
    secure: RX8XueSBJ7UsROpWlM1Zf/D+n2ctWY+w3DhuM7I07/Tc9I3xn9N0Tg4SK7Kdq8jv0VlcowBYX2QTkBhqmc73nza8SLYNEtOkJ9wv/SnSvqQ84GECX+AgM7EnRZ9Tt+Da13/KI4TpVWL41hE7Eh0STUA2HCNIDXgUnIBD6ntu/zU=
  on:
    tags: true
    repo: locationlabs/docker-debug
